[package]
name = "easy-fs"
version = "0.1.0"

[dependencies]
spin = "0.7.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }

[profile.release]
debug = true

[features]
default = ["board_qemu"]
board_qemu = []
board_k210 = []